---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
        - javascript

exclude_paths:
  - tests/
  - dist/

...

/* vim: set expandtab shiftwidth=2 softtabstop=2: */
