image: js-testing

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - export NODE_ENV="testing"
    - npm install
    - grunt uglify

unit_tests:
  stage: test
  script:
    - export NODE_ENV="testing"
    - npm install
    - grunt unit

coverage_tests:
  stage: test
  script:
    - export NODE_ENV="testing"
    - npm install
    - grunt --verbose coverage
  allow_failure: true
