image: dr.codingallnight.com/chris/docker-builds:js-testing

stages:
  - test
  - build

variables:
  NODE_ENV: "testing"

before_script:
  - npm config set cache /npm-cache --global
  - npm install

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - rm dist/.gitkeep # Keep this file out of the build artifacts
    - grunt uglify
    - grunt qunit:dist # Test the uglified files

unit_tests:
  stage: test
  script:
    - grunt unit

coverage_tests:
  stage: test
  script:
    - grunt --verbose coverage
  allow_failure: true
