image: js-testing

stages:
  - test

unit_tests:
  stage: test
  script:
    - export NODE_ENV="testing"
    - npm install
    - grunt unit

coverage_tests:
  stage: test
  script:
    - export NODE_ENV="testing"
	- npm install
	- grunt --verbose coverage
  allow_failure: true
